# python cơ bản
# print("Hello World")
# a = 5
# b = 10
# c = a + b
# print("Tổng của a và b là:", c)

#Bài 1 : 
# a = int(input("Nhập một số tự nhiên a: "))
# b = int(input("Nhập một số tự nhiên b: "))
# c = a + b
# print("Tổng của a và b là:", c)
# d = a * b
# print("Tích của a và b là:", d)
# e = a / b
# print("Thương của a và b là:", e)
# f = a - b
# print("Hiệu của a và b là:", f)

#Bài 2:
# sum = 0
# input_number = int(input("Nhập một số tự nhiên: "))
# if input_number >= 0:
#     sum += 1
#     print("Tổng hiện tại là:", sum)
# else:
#     print("Vui lòng nhập số tự nhiên.")

